### ISSUE TITLE
Request Feature needs to be implemented

### ISSUE THREAD

**Issue by beanbash** [hedges7/gmodtransfer#1]
Request is already working. When you click request net messages are sent and received etc etc. 

The only issue is for the player to accept the request

**Comment by Pdzly** [comment]
I would like to implement that!

**Comment by beanbash** [comment]
> I would like to implement that! 
> 
> 

Go absolutely ahead 😄

I had at first attempted to create a menu pop-up in the top center of the screen saying

"Would you like to accept this request for (amount) (name)" etc.

But the problem was it kept creating new elements infinitely (buttons, labels) Most likely something with net library and how I did it but feel free to school me 😂

**Comment by Pdzly** [comment]
For the first iteration i would just keep it as a chat message

**Comment by Pdzly** [comment]
https://github.com/Pdzly/gmodtransfer

You can track my changes here
I refactored some of your code too ( or made parts possible )

If you want to talk about the changes just hit me up in discord: Rooki#0187
I would really like to talk ;)

But tomorrow! Today its to late for me ;)

**Comment by beanbash** [comment]
> For the first iteration i would just keep it as a chat message
> 

Yea I figured, it can be implemented later on

**Comment by beanbash** [comment]
> https://github.com/Pdzly/gmodtransfer
> 
> You can track my changes here
> I refactored some of your code too ( or made parts possible )
> 
> If you want to talk about the changes just hit me up in discord: Rooki#0187
> I would really like to talk ;)
> 
> But tomorrow! Today its to late for me ;)

Make sure your accepting friend requests so I can add you.

And that sounds good, thanks for your help!

**Comment by Pdzly** [comment]
> > https://github.com/Pdzly/gmodtransfer
> > You can track my changes here
> > I refactored some of your code too ( or made parts possible )
> > If you want to talk about the changes just hit me up in discord: Rooki#0187
> > I would really like to talk ;)
> > But tomorrow! Today its to late for me ;)
> 
> Make sure your accepting friend requests so I can add you.
> 
> And that sounds good, thanks for your help!

yup, if you make one i will accept one ( right now no friend request came to me )

**Comment by beanbash** [comment]
> > > https://github.com/Pdzly/gmodtransfer
> > > You can track my changes here
> > > I refactored some of your code too ( or made parts possible )
> > > If you want to talk about the changes just hit me up in discord: Rooki#0187
> > > I would really like to talk ;)
> > > But tomorrow! Today its to late for me ;)
> > 
> > Make sure your accepting friend requests so I can add you.
> > 
> > And that sounds good, thanks for your help!
> 
> yup, if you make one i will accept one ( right now no friend request came to me )

You have them turned off, or had. I haven't checked yet

mine is Hedges#3616

**Comment by beanbash** [comment]
Request feature is implemented just buggy as of now 👍

**Comment by Pdzly** [comment]
Not Buggy ;)
