### ISSUE TITLE
Chat commands are broken.

### ISSUE THREAD

**Issue by PossiblyCharles** [hedges7/gmodtransfer#11]
Chat commands are broken.

Already closed and removed addon as I'm messing with other stuff... But error was along the lines of "StartsWith" being nil in a sv_ file.

**Comment by Pdzly** [comment]
Yeah because it is just stupid StartWith

**Comment by Pdzly** [comment]
https://wiki.facepunch.com/gmod/string.StartsWith

Because StartsWith is only in dev branch. fixed now
